
# Site settings
title: Steph Explores
description: I'm a web man... just like my pappy... and my pappy's pappy.
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: stephanie.paige@hotmail.com
baseurl: "/"
url: "https://nates.work" # the base hostname & protocol for your site
social:
  #instagram: https://www.instagram.com/stephanie_paigee/
  #youtube: https://www.youtube.com/channel/UCcrrpGUoDCTznp0YKyo3O3Q
  #pinterest: https://www.pinterest.com/stephexplores/
  #email: /contact/

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
